W0219 07:13:36.355000 3362 torch/distributed/run.py:793] 
W0219 07:13:36.355000 3362 torch/distributed/run.py:793] *****************************************
W0219 07:13:36.355000 3362 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0219 07:13:36.355000 3362 torch/distributed/run.py:793] *****************************************
4: thread affinity: {64, 192, 68, 196, 72, 200, 76, 204, 80, 208, 84, 212, 88, 216, 92, 220, 96, 224, 248, 100, 228, 104, 232, 108, 236, 112, 240, 116, 244, 252, 120, 124}
7: thread affinity: {255, 67, 195, 71, 199, 75, 203, 79, 207, 83, 211, 87, 215, 91, 219, 247, 95, 223, 99, 227, 103, 231, 107, 235, 111, 239, 251, 115, 243, 119, 123, 127}
2: thread affinity: {2, 130, 6, 134, 10, 138, 14, 142, 18, 146, 22, 150, 26, 154, 30, 158, 34, 162, 38, 166, 42, 170, 46, 174, 50, 178, 54, 182, 58, 186, 62, 190}
6: thread affinity: {66, 194, 70, 198, 74, 202, 78, 206, 82, 210, 254, 86, 214, 90, 218, 94, 222, 98, 226, 102, 230, 106, 234, 250, 110, 238, 114, 242, 118, 246, 122, 126}
0: thread affinity: {0, 128, 4, 132, 8, 136, 12, 140, 16, 144, 20, 148, 24, 152, 28, 156, 32, 160, 36, 164, 40, 168, 44, 172, 48, 176, 52, 180, 56, 184, 60, 188}
3: thread affinity: {3, 131, 7, 135, 11, 139, 15, 143, 19, 147, 23, 151, 27, 155, 31, 159, 35, 163, 39, 167, 43, 171, 47, 175, 51, 179, 55, 183, 59, 187, 63, 191}
1: thread affinity: {1, 129, 5, 133, 9, 137, 13, 141, 17, 145, 21, 149, 25, 153, 29, 157, 33, 161, 37, 165, 41, 169, 45, 173, 49, 177, 53, 181, 57, 185, 61, 189}
5: thread affinity: {65, 193, 69, 197, 73, 201, 77, 205, 81, 209, 85, 213, 89, 217, 93, 221, 253, 97, 225, 101, 229, 249, 105, 233, 109, 237, 113, 241, 117, 245, 121, 125}
[rank4]:[W219 07:14:28.254132458 ProcessGroupNCCL.cpp:4088] [PG ID 0 PG GUID 0 Rank 4]  using GPU 4 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank6]:[W219 07:14:29.687184886 ProcessGroupNCCL.cpp:4088] [PG ID 0 PG GUID 0 Rank 6]  using GPU 6 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank5]:[W219 07:14:29.792045676 ProcessGroupNCCL.cpp:4088] [PG ID 0 PG GUID 0 Rank 5]  using GPU 5 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank1]:[W219 07:14:29.018864405 ProcessGroupNCCL.cpp:4088] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank2]:[W219 07:14:29.435953141 ProcessGroupNCCL.cpp:4088] [PG ID 0 PG GUID 0 Rank 2]  using GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank7]:[W219 07:14:29.446766194 ProcessGroupNCCL.cpp:4088] [PG ID 0 PG GUID 0 Rank 7]  using GPU 7 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank3]:[W219 07:14:29.453103038 ProcessGroupNCCL.cpp:4088] [PG ID 0 PG GUID 0 Rank 3]  using GPU 3 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
Experiment dir : LM-TFM
[rank0]:[W219 07:14:29.460764474 ProcessGroupNCCL.cpp:4088] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
Namespace(work_dir='LM-TFM', append_dataset=False, append_time=False, cuda=True, fp16=False, restart='', debug=False, log_all_ranks=False, dllog_file='train_log.json', txtlog_file='train_log.log', save_all=False, no_env=False, no_eval=True, no_test=False, log_interval=10, target_throughput=None, target_perplexity=None, apex_amp_opt_level='O2', amp='apex', affinity='socket_unique_interleaved', data='/data/transformer-xl/wikitext-103', dataset='wt103', vocab='word', n_layer=18, n_head=16, d_head=64, d_embed=1024, d_model=1024, d_inner=4096, dropout=0.2, dropatt=0.2, pre_lnorm=False, attn_type=0, not_tied=False, clamp_len=-1, adaptive=False, div_val=1, sample_softmax=-1, init='normal', emb_init='normal', init_range=0.1, emb_init_range=0.01, init_std=0.02, proj_init_std=0.01, optim='adam', lr=0.0, mom=0.0, scheduler='cosine', max_step_scheduler=None, warmup_step=16000, decay_rate=0.5, lr_min=0.0, clip=0.25, weight_decay=0.0, clip_nonemb=False, patience=0, eta_min=0.001, max_step=400, batch_size=384, local_batch_size=None, batch_chunk=1, roll=True, tgt_len=256, ext_len=0, mem_len=256, seed=1111, multi_gpu=None, gpu0_bsz=-1, same_length=False, varlen=False, swap_mem=False, eval_tgt_len=128, eval_batch_size=16, eval_max_steps=-1, eval_interval=5000, local_rank=0, tied=True)
world size: 8
Collecting environment information...
[rank1]: Traceback (most recent call last):
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank1]:     main()
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank1]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank1]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank1]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank1]:     assert os.path.exists(path)
[rank1]: AssertionError
[rank4]: Traceback (most recent call last):
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank4]:     main()
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank4]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank4]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank4]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank4]:     assert os.path.exists(path)
[rank4]: AssertionError
[rank7]: Traceback (most recent call last):
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank7]:     main()
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank7]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank7]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank7]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank7]:     assert os.path.exists(path)
[rank7]: AssertionError
[rank3]: Traceback (most recent call last):
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank3]:     main()
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank3]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank3]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank3]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank3]:     assert os.path.exists(path)
[rank3]: AssertionError
[rank6]: Traceback (most recent call last):
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank6]:     main()
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank6]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank6]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank6]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank6]:     assert os.path.exists(path)
[rank6]: AssertionError
W0219 07:15:16.299000 3362 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 3429 closing signal SIGTERM
W0219 07:15:16.299000 3362 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 3431 closing signal SIGTERM
W0219 07:15:16.299000 3362 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 3432 closing signal SIGTERM
W0219 07:15:16.300000 3362 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 3433 closing signal SIGTERM
W0219 07:15:16.300000 3362 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 3434 closing signal SIGTERM
W0219 07:15:16.300000 3362 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 3435 closing signal SIGTERM
W0219 07:15:16.300000 3362 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 3436 closing signal SIGTERM
E0219 07:15:20.790000 3362 torch/distributed/elastic/multiprocessing/api.py:862] failed (exitcode: 1) local_rank: 1 (pid: 3430) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.5.0a0+e000cf0ad9.nv24.10', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-19_07:15:16
  host      : 28e64133fdab
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3430)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
DONE!
